config {
    type: "view"
}

WITH
  base AS(
  SELECT
    *
  FROM
    `healthtree-production.HT_test_sync.apps-curehub-medicalResources-r4-Observation`
  WHERE
    fhir IS NOT NULL
    AND user.id IN (
    SELECT
      person_source_value
    FROM
      ${ref("allPersons")})
    AND (fhir.valueQuantity IS NOT NULL) )

      
SELECT
  user.id AS person_source_value,
  fhir.id AS record_source_id,
  COALESCE(fhir.effectiveDateTime, CAST(fhir.issued AS STRING)) AS measurement_DATE,
  SAFE_CAST(fhir.valueQuantity.value AS FLOAT64) AS value_as_number,
  fhir.valueQuantity.value AS value_source_value,
  fhir.valueQuantity.unit AS unit_source_value,
  COALESCE(fhir.referenceRange[SAFE_OFFSET(0)].low.value) AS range_low,
  COALESCE(fhir.referenceRange[SAFE_OFFSET(0)].high.value) AS range_high,
  CASE WHEN STARTS_WITH(fhir.encounter.reference, "Encounter/") THEN 
  SPLIT(fhir.encounter.reference, "Encounter/")[OFFSET(1)]
ELSE 
  NULL 
END AS visit_occurrence_reference,
  fhir.encounter.reference AS visit_occurrence_type,
  mcu.display AS measurement_source_value,
  mcu.code AS measurement_source_code,
  mcu.system AS measurement_source_system,
  COALESCE(fhir.category[SAFE_OFFSET(0)].text, fhir.category[SAFE_OFFSET(0)].coding[SAFE_OFFSET(0)].display) AS measurement_source_type,
  fhir.status AS measurement_source_status
FROM
  base AS b
JOIN
  ${ref("meas_code_unnested")} AS mcu
ON
  b.user.id = mcu.person_source_value
  AND b.fhir.id = mcu.record_source_id
