config {
    type: "view"
}

WITH
  base AS(
  SELECT
    *
  FROM
    `healthtree-production.HT.Observation`
  WHERE
    fhir IS NOT NULL
    AND user.name IN (
    SELECT
      person_source_value
    FROM
      ${ref("allPersons")})
    AND (fhir.valueQuantity IS NOT NULL
      OR fhir.valueRange IS NOT NULL) )

      
SELECT
  user.name AS person_source_value,
  fhir.id AS record_source_id,
  COALESCE(fhir.effectiveDateTime.string, CAST(fhir.effectiveDateTime.date_time AS STRING), CAST(fhir.issued AS STRING), fhir.effectivePeriod.start) AS measurement_DATE,
  COALESCE(CAST(fhir.valueQuantity.value.float AS STRING), CAST(fhir.valueQuantity.value.integer AS STRING), fhir.valueQuantity.value.string) AS value_as_number,
  COALESCE(CAST(fhir.valueQuantity.value.float AS STRING), CAST(fhir.valueQuantity.value.integer AS STRING), fhir.valueQuantity.value.string) AS value_source_value,
  COALESCE(fhir.valueQuantity.unit.string, CAST(fhir.valueQuantity.unit.integer AS STRING)) AS unit_source_value,
  COALESCE(fhir.referenceRange[SAFE_OFFSET(0)].low.value.float, fhir.referenceRange[SAFE_OFFSET(0)].low.value.integer, fhir.valueRange.low.value.float, fhir.valueRange.low.value.integer) AS range_low,
  COALESCE(fhir.referenceRange[SAFE_OFFSET(0)].high.value.float, fhir.referenceRange[SAFE_OFFSET(0)].high.value.integer, fhir.valueRange.high.value, fhir.valueRange.high.value) AS range_high,
  CASE WHEN STARTS_WITH(fhir.encounter.reference, "Encounter/") THEN 
  SPLIT(fhir.encounter.reference, "Encounter/")[OFFSET(1)]
ELSE 
  NULL 
END AS visit_occurrence_reference,
  fhir.encounter.display AS visit_occurrence_type,
  mcu.display AS measurement_source_value,
  mcu.code AS measurement_source_code,
  mcu.system AS measurement_source_system,
  COALESCE(fhir.category[SAFE_OFFSET(0)].text, fhir.category[SAFE_OFFSET(0)].coding[SAFE_OFFSET(0)].display) AS measurement_source_type,
  fhir.status AS measurement_source_status
FROM
  base AS b
JOIN
  ${ref("meas_code_unnested")} AS mcu
ON
  b.user.name = mcu.person_source_value
  AND b.fhir.id = mcu.record_source_id
