config {
    type: "view"
}
WITH
  base AS (
  SELECT
    *
  FROM
    `healthtree-production.HT_test_sync.apps-curehub-medicalResources-r4-MedicationRequest`
  WHERE
    fhir IS NOT NULL
    AND user.id IN (
    SELECT
      person_source_value
    FROM
      ${ref("allPersons")}) )


select mt.user.id as person_source_value,
mt.fhir.id as record_source_id,
coalesce(
  mt.fhir.medicationCodeableConcept.coding[SAFE_OFFSET(0)].code,
  mt.fhir.contained[SAFE_OFFSET(0)].ingredient[SAFE_OFFSET(0)].itemCodeableConcept.coding[SAFE_OFFSET(0)].code,
  mt.fhir.medicationReference.reference ) as drug_source_code,
coalesce(
  mt.fhir.medicationCodeableConcept.coding[SAFE_OFFSET(0)].display,
  mt.fhir.contained[SAFE_OFFSET(0)].ingredient[SAFE_OFFSET(0)].itemCodeableConcept.coding[SAFE_OFFSET(0)].display,
  mt.fhir.medicationReference.display
) as drug_source_value,
coalesce(
  mt.fhir.medicationCodeableConcept.coding[SAFE_OFFSET(0)].system,
  mt.fhir.contained[SAFE_OFFSET(0)].ingredient[SAFE_OFFSET(0)].itemCodeableConcept.coding[SAFE_OFFSET(0)].system
) as drug_source_system,
coalesce(
  mt.fhir.dosageInstruction[SAFE_OFFSET(0)].timing.repeat.boundsPeriod.start, mt.fhir.dispenseRequest.validityPeriod.start,
  mt.fhir.authoredOn
  ) as drug_exposure_start_DATE,
  coalesce(
  mt.fhir.dosageInstruction[SAFE_OFFSET(0)].timing.repeat.boundsPeriod.end, mt.fhir.dispenseRequest.validityPeriod.end
  ) as drug_exposure_end_DATE,
  COALESCE(mt.fhir.dispenseRequest.quantity.value,
  mt.fhir.dosageInstruction[SAFE_OFFSET(0)].doseAndRate[SAFE_OFFSET(0)].doseQuantity.value) as quantity,
  COALESCE(mt.fhir.dispenseRequest.quantity.unit, mt.fhir.dosageInstruction[SAFE_OFFSET(0)].doseAndRate[SAFE_OFFSET(0)].doseQuantity.unit,
  CAST(mt.fhir.dosageInstruction[SAFE_OFFSET(0)].doseAndRate[SAFE_OFFSET(0)].doseQuantity.unit as STRING)) as dose_unit_source_value,
  CASE WHEN mt.fhir.dispenseRequest.expectedSupplyDuration.code like "d" THEN mt.fhir.dispenseRequest.expectedSupplyDuration.value
  ELSE NULL END as days_supply,
  mt.fhir.encounter.reference as visit_occurrence_reference,
  mt.fhir.encounter.display as visit_occurrence_type,
mt.fhir.category[SAFE_OFFSET(0)].text as drug_source_category,
mt.fhir.status as drug_source_status,
COALESCE(mt.fhir.dosageInstruction[SAFE_OFFSET(0)].route.text, mt.fhir.dosageInstruction[SAFE_OFFSET(0)].route.coding[SAFE_OFFSET(0)].display)
as route_source_value,
COALESCE(mt.fhir.dosageInstruction[SAFE_OFFSET(0)].route.coding[SAFE_OFFSET(0)].code) as route_source_code,
from `healthtree-production.HT_test_sync.apps-curehub-medicalResources-r4-MedicationRequest` AS mt LEFT JOIN `healthtree-production.HT.MedicationRequest` AS ref_table
ON mt.id = ref_table.__key__.name AND ref_table.fhir IS NULL
where mt.fhir is not null and mt.source.name != "HEALTH_TREE" and
(mt.fhir.medicationCodeableConcept is not null or mt.fhir.medicationReference is not null or ARRAY_LENGTH(mt.fhir.contained) > 0)
and mt.fhir.status != "entered-in-error"
