config {
  type: "view"
}
/*
SELECT 
  dei.* EXCEPT(drug_concept_id),
  COALESCE(dmm.concept_id, dei.drug_concept_id) AS drug_concept_id
FROM ${ref("drug_exposure_inter")} dei
LEFT JOIN ${ref("drug_manualMappings")} dmm
  ON dei.drug_concept_id = 0
  AND LOWER(dei.drug_source_value) LIKE CONCAT('%', LOWER(dmm.drug_name), '%')
*/
with base as (
SELECT * FROM ${ref("new_drug_exposure3")}
WHERE person_source_value in (
    SELECT
      person_source_value
    FROM
      ${ref("allPersons")})
)

select 
ROW_NUMBER() OVER (ORDER BY (Select null)) as drug_exposure_id,
p.person_id as person_id,
p.person_source_value as person_source_value,
dv.record_source_id as record_source_id,
COALESCE(concept.concept_id, 0) as drug_concept_id,
dv.drug_exposure_start_DATE as drug_exposure_start_DATE,
dv.drug_exposure_start_DATETIME as drug_exposure_start_DATETIME,
dv.drug_exposure_end_DATE as drug_exposure_end_DATE,
dv.drug_exposure_end_DATETIME as drug_exposure_end_DATETIME,
dv.verbatim_end_DATE as verbatim_end_DATE,
null as drug_type_concept_id,
null as stop_reason,
null as refills,
dv.quantity as quantity,
dv.days_supply as days_supply,
dv.sig as sig,
null as route_concept_id,
null as lot_number,
null as provider_id,
null as visit_occurrence_id,
null as visit_detail_id,
dv.drug_source_value as drug_source_value,
dv.drug_source_concept_id as drug_source_concept_id,
dv.route_source_value as route_source_value,
dv.dose_unit_source_value as dose_unit_source_value,

dv.visit_occurrence_reference as visit_occurrence_reference,
dv.visit_occurrence_type as visit_occurrence_type,
dv.drug_source_code as drug_source_code,
dv.drug_source_system as drug_source_system,
dv.drug_source_status as drug_source_status,
dv.drug_source_category as drug_source_category

from ${ref("new_drug_exposure3")} dv join ${ref("person")} p on dv.person_source_value = p.person_source_value
LEFT JOIN ${ref("vocabulary_mapping")} vm ON
LOWER(dv.drug_source_system) LIKE "%" || LOWER(vm.search_record) || "%"
LEFT JOIN `healthtree-production.OMOP.Concept` concept ON
concept.concept_code = dv.drug_source_code
