config {
    type: "table"
}

select 
ROW_NUMBER() OVER (ORDER BY (Select null)) as drug_exposure_id,
p.person_id as person_id,
p.person_source_value as person_source_value,
dv.record_source_id as record_source_id,
null as drug_concept_id,
dv.drug_exposure_start_DATE as drug_exposure_start_DATE,
null as drug_exposure_start_DATETIME,
dv.drug_exposure_end_DATE as drug_exposure_end_DATE,
null as drug_exposure_end_DATETIME,
null as verbatim_end_DATE,
null as drug_type_concept_id,
null as stop_reason,
null as refills,
dv.quantity as quantity,
dv.days_supply as days_supply,
null as sig,
null as route_concept_id,
null as lot_number,
null as provider_id,
null as visit_occurrence_id,
null as visit_detail_id,
dv.drug_source_value as drug_source_value,
null as drug_source_concept_id,
dv.route_source_value as route_source_value,
dv.dose_unit_source_value as dose_unit_source_value,

dv.visit_occurrence_reference as visit_occurrence_reference,
dv.visit_occurrence_type as visit_occurrence_type,
dv.drug_source_code as drug_source_code,
dv.drug_source_system as drug_source_system,
dv.drug_source_status as drug_source_status,
dv.drug_source_category as drug_source_category


from ${ref("drug_exposure_valid")} dv join ${ref("person")} p on dv.person_source_value = p.person_source_value