config {
  type: "table"
}

SELECT *
FROM UNNEST([
  STRUCT(
    CAST(NULL AS INT64) AS cost_id,
    CAST(NULL AS INT64) AS cost_event_id,
    CAST(NULL AS STRING) AS cost_domain_id,
    CAST(NULL AS INT64) AS cost_type_concept_id,
    CAST(NULL AS INT64) AS currency_concept_id,
    CAST(NULL AS NUMERIC) AS total_charge,
    CAST(NULL AS NUMERIC) AS total_cost,
    CAST(NULL AS NUMERIC) AS total_paid,
    CAST(NULL AS NUMERIC) AS paid_by_payer,
    CAST(NULL AS NUMERIC) AS paid_by_patient,
    CAST(NULL AS NUMERIC) AS paid_patient_copay,
    CAST(NULL AS NUMERIC) AS paid_patient_coinsurance,
    CAST(NULL AS NUMERIC) AS paid_patient_deductible,
    CAST(NULL AS NUMERIC) AS paid_by_primary,
    CAST(NULL AS NUMERIC) AS paid_ingredient_cost,
    CAST(NULL AS NUMERIC) AS paid_dispensing_fee,
    CAST(NULL AS NUMERIC) AS payer_plan_period_id,
    CAST(NULL AS NUMERIC) AS amount_allowed,
    CAST(NULL AS NUMERIC) AS revenue_code_concept_id,
    CAST(NULL AS STRING) AS revenue_code_source_value,
    CAST(NULL AS INT64) AS drg_concept_id,
    CAST(NULL AS STRING) AS drg_source_value
  )
])
WHERE FALSE
