config {
  type: "table"
}

SELECT *
FROM UNNEST([
  STRUCT(
    CAST(NULL AS INT64)  AS location_id,
    CAST(NULL AS STRING) AS address_1,
    CAST(NULL AS STRING) AS address_2,
    CAST(NULL AS STRING) AS city,
    CAST(NULL AS STRING) AS state,
    CAST(NULL AS STRING) AS zip,
    CAST(NULL AS STRING) AS county,
    CAST(NULL AS STRING) AS location_source_value,
    CAST(NULL AS INT64) AS country_concept_id,
    CAST(NULL AS STRING) AS country_source_value,
    CAST(NULL AS FLOAT64) AS latitude,
    CAST(NULL AS FLOAT64) AS longitude
  )
])
WHERE FALSE
