config {
  type: "table"
}

SELECT *
FROM UNNEST([
  STRUCT(
    CAST(NULL AS INT64) AS note_nlp_id,
    CAST(NULL AS INT64) AS note_id,
    CAST(NULL AS INT64) AS section_concept_id,
    CAST(NULL AS STRING) AS snippet,
    CAST(NULL AS STRING) AS offset,
    CAST(NULL AS INT64) AS lexical_variant,
    CAST(NULL AS INT64) AS note_nlp_concept_id,
    CAST(NULL AS INT64) AS note_nlp_source_concept_id,
    CAST(NULL AS STRING) AS nlp_system,
    CAST(NULL AS DATE) AS nlp_date,
    CAST(NULL AS DATETIME) AS nlp_datetime,
    CAST(NULL AS STRING) AS term_exists,
    CAST(NULL AS STRING) AS term_temporal,
    CAST(NULL AS STRING) AS term_modifiers
  )
]
)
WHERE FALSE
