config {
  type: "table"
}

SELECT *
FROM UNNEST([
  STRUCT(
    CAST(NULL AS INT64)  AS payer_plan_period_id,
    CAST(NULL AS INT64)  AS person_id,
    CAST(NULL AS DATE)   AS payer_plan_period_start_date,
    CAST(NULL AS DATE)   AS payer_plan_period_end_date,
    CAST(NULL AS INT64)  AS payer_concept_id,
    CAST(NULL AS INT64)  AS payer_source_concept_id,
    CAST(NULL AS STRING) AS payer_source_value,
    CAST(NULL AS INT64)  AS plan_concept_id,
    CAST(NULL AS INT64)  AS plan_source_concept_id,
    CAST(NULL AS STRING) AS plan_source_value,
    CAST(NULL AS INT64)  AS sponsor_concept_id,
    CAST(NULL AS INT64)  AS sponsor_source_concept_id,
    CAST(NULL AS STRING) AS sponsor_source_value,
    CAST(NULL AS INT64)  AS family_source_value,
    CAST(NULL AS INT64)  AS stop_reason_concept_id,
    CAST(NULL AS STRING) AS stop_reason_source_value
  )
])
WHERE FALSE
