config {
  type: "table"
}

SELECT *
FROM UNNEST([
  STRUCT(
    CAST(NULL AS INT64)    AS specimen_id,
    CAST(NULL AS INT64)    AS person_id,
    CAST(NULL AS INT64)    AS specimen_concept_id,
    CAST(NULL AS DATE)     AS specimen_date,
    CAST(NULL AS DATETIME) AS specimen_datetime,
    CAST(NULL AS INT64)    AS specimen_type_concept_id,
    CAST(NULL AS STRING)   AS specimen_source_id,
    CAST(NULL AS FLOAT64)  AS unit_concept_id,
    CAST(NULL AS FLOAT64)  AS quantity,
    CAST(NULL AS INT64)    AS anatomic_site_concept_id,
    CAST(NULL AS INT64)    AS disease_status_concept_id,
    CAST(NULL AS STRING)   AS specimen_source_value,
    CAST(NULL AS STRING)   AS unit_source_value,
    CAST(NULL AS STRING)   AS anatomic_site_source_value,
    CAST(NULL AS STRING)   AS disease_status_source_value
  )
])
WHERE FALSE
