config {
  type: "table"
}

SELECT *
FROM UNNEST([
  STRUCT(
    CAST(NULL AS INT64) AS visit_detail_id,
    CAST(NULL AS INT64) AS person_id,
    CAST(NULL AS INT64) AS visit_detail_concept_id,
    CAST(NULL AS DATE) AS visit_detail_start_date,
    CAST(NULL AS DATETIME) AS visit_detail_start_datetime,
    CAST(NULL AS DATE) AS visit_detail_end_date,
    CAST(NULL AS DATETIME) AS visit_detail_end_datetime,
    CAST(NULL AS INT64) AS visit_detail_type_concept_id,
    CAST(NULL AS INT64) AS provider_id,
    CAST(NULL AS INT64) AS care_site_id,
    CAST(NULL AS STRING) AS visit_detail_source_value,
    CAST(NULL AS INT64) AS visit_detail_source_concept_id,
    CAST(NULL AS INT64) AS admitted_from_concept_id,
    CAST(NULL AS STRING) AS admitted_from_source_value,
    CAST(NULL AS INT64) AS discharge_to_concept_id,
    CAST(NULL AS STRING) AS discharge_to_source_value,
    CAST(NULL AS INT64) AS preceding_visit_detail_id,
    CAST(NULL AS INT64) AS parent_visit_detail_id,
    CAST(NULL AS INT64) AS visit_occurrence_id
  )
])
WHERE FALSE
