config {
    type: "view"
}

with base as (
select patient_id,
display as race_source_value,
code as race_source_concept_id
from ${ref("person_demographics")} where (url like "%race%") and display is not null
),

Intermediate as
(
SELECT 
    patient_id,
ARRAY_AGG(CASE WHEN LOWER(race_source_value) like "%white%" or LOWER(race_source_value) like "%black%"
    or LOWER(race_source_value) like "%asian%" or LOWER(race_source_value) like "%african%" then race_source_value
    WHEN LOWER(race_source_value) like "%unknown%" or LOWER(race_source_value) like "%other%" or
    LOWER(race_source_value) like "%decline%" then null
    else race_source_value end
    IGNORE NULLS)[SAFE_OFFSET(0)]
    AS race_source_value,
    CASE WHEN LOWER(ARRAY_AGG(race_source_value IGNORE NULLS)[SAFE_OFFSET(0)]) like "%white%" THEN 8527
    WHEN LOWER(ARRAY_AGG(race_source_value IGNORE NULLS)[SAFE_OFFSET(0)]) like "%black%" THEN 8516
    WHEN LOWER(ARRAY_AGG(race_source_value IGNORE NULLS)[SAFE_OFFSET(0)]) like "%asian%" THEN 8515
    WHEN LOWER(ARRAY_AGG(race_source_value IGNORE NULLS)[SAFE_OFFSET(0)]) like "%african%" THEN 8516
    WHEN LOWER(ARRAY_AGG(race_source_value IGNORE NULLS)[SAFE_OFFSET(0)]) like "%unknown%" THEN 8552
    WHEN LOWER(ARRAY_AGG(race_source_value IGNORE NULLS)[SAFE_OFFSET(0)]) like "%other%" THEN 8522
    WHEN LOWER(ARRAY_AGG(race_source_value IGNORE NULLS)[SAFE_OFFSET(0)]) like "%decline%" THEN 0
    WHEN LOWER(ARRAY_AGG(race_source_value IGNORE NULLS)[SAFE_OFFSET(0)]) like "%american indian%" THEN 38003572
    ELSE 0 END
    AS race_source_concept_id
FROM 
    base
GROUP BY 
    patient_id
)

SELECT * EXCEPT(race_source_concept_id),
    CASE WHEN LOWER(race_source_value) like "%white%" THEN 8527
    WHEN LOWER(race_source_value) like "%black%" THEN 8516
    WHEN LOWER(race_source_value) like "%asian%" THEN 8515
    WHEN LOWER(race_source_value) like "%african%" THEN 8516
    WHEN LOWER(race_source_value) like "%unknown%" THEN 8552
    WHEN LOWER(race_source_value) like "%other%" THEN 8522
    WHEN LOWER(race_source_value) like "%decline%" THEN 0
    WHEN LOWER(race_source_value) like "%american indian%" THEN 38003572
    ELSE 0 END
    AS race_source_concept_id
FROM Intermediate
