config {
    type: "view"
}

with base as(
select * from `healthtree-production.HT_test_sync.apps-curehub-medicalResources-r4-Procedure` where fhir is not null and user.id in
(Select person_source_value from ${ref("allPersons")})
),

intermediate as (
SELECT 
user.id as person_source_value,
id as record_source_id,
fhir.id as fhir_record_id,

SAFE.PARSE_DATE(
    '%Y-%m-%d',
    CASE
      -- 2022          → 2022-01-01
      WHEN REGEXP_CONTAINS(fhir.performedDateTime, r'^\d{4}$')
        THEN CONCAT(fhir.performedDateTime, '-01-01')

      -- 2022-03       → 2022-03-01
      WHEN REGEXP_CONTAINS(fhir.performedDateTime, r'^\d{4}-\d{2}$')
        THEN CONCAT(fhir.performedDateTime, '-01')

      -- 2022-03-15    → 2022-03-15
      WHEN REGEXP_CONTAINS(fhir.performedDateTime, r'^\d{4}-\d{2}-\d{2}$')
        THEN fhir.performedDateTime

      -- 2022-03-15 ... (cualquier fecha-hora) → usa solo los 10 primeros char
      WHEN REGEXP_CONTAINS(fhir.performedDateTime, r'^\d{4}-\d{2}-\d{2}[ T]')
        THEN SUBSTR(fhir.performedDateTime, 1, 10)

      ELSE NULL   -- Todo lo demás (foo, cadenas vacías, etc.)
    END
  )

 as procedure_DATE,
CASE WHEN STARTS_WITH(fhir.encounter.reference, "Encounter/") THEN 
  SPLIT(fhir.encounter.reference, "Encounter/")[OFFSET(1)]
ELSE 
  NULL 
END AS visit_occurrence_reference,
fhir.status as procedure_source_status,
COALESCE(
    fhir.category.text, (SELECT coding.display from UNNEST(fhir.category.coding) as coding)
) as procedure_source_type,
(SELECT coding.code from UNNEST(fhir.category.coding) as coding) as procedure_source_type_code,
coding.system as procedure_source_system,
coding.display as procedure_source_value,
coding.code as procedure_source_code

FROM base, UNNEST(fhir.code.coding) as coding
)

SELECT * EXCEPT(procedure_source_code),
procedure_source_code AS procedure_source_concept_id
FROM intermediate

