config {
    type: "view"
}

with base as(
select * from `healthtree-production.HT_test_sync.apps-curehub-medicalResources-r4-Procedure` where fhir is not null and user in
(Select person_source_value from ${ref("allPersons")})
)

SELECT 
user as person_source_value,
fhir.id as record_source_id,
DATE(fhir.performedDateTime) as procedure_DATE,
CASE WHEN STARTS_WITH(fhir.encounter.reference, "Encounter/") THEN 
  SPLIT(fhir.encounter.reference, "Encounter/")[OFFSET(1)]
ELSE 
  NULL 
END AS visit_occurrence_reference,
fhir.status as procedure_source_status,
COALESCE(
    fhir.category.text, (SELECT coding.display from UNNEST(fhir.category.coding) as coding)
) as procedure_source_type,
(SELECT coding.code from UNNEST(fhir.category.coding) as coding) as procedure_source_type_code,
COALESCE(fhir.code.text, (SELECT coding.display from UNNEST(fhir.code.coding) as coding where LOWER(coding.system) like "%snomed%" or
LOWER(coding.system) like "%loinc%" or LOWER(coding.system) like "%icd-9%" or LOWER(coding.system) like "%icd-10%" limit 1)) as procedure_source_value,
(SELECT 
coding.code as code
 from UNNEST(fhir.code.coding) as coding where LOWER(coding.system) like "%snomed%" or
LOWER(coding.system) like "%loinc%" or LOWER(coding.system) like "%icd-9%" or LOWER(coding.system) like "%icd-10%" limit 1) as procedure_source_concept_id

from base 
