config {
    type: "view"
}

with base as(
select * from `healthtree-production.HT.Procedure` where fhir is not null and user.name in
(Select person_source_value from ${ref("allPersons")})
),

intermediate as (
SELECT 
user.name as person_source_value,
fhir.id as record_source_id,
COALESCE(
fhir.performedDateTime.string,
STRING(fhir.performedDateTime.date_time),
fhir.performedPeriod.start
) as procedure_DATE,
CASE WHEN STARTS_WITH(fhir.encounter.reference, "Encounter/") THEN 
  SPLIT(fhir.encounter.reference, "Encounter/")[OFFSET(1)]
ELSE 
  NULL 
END AS visit_occurrence_reference,
fhir.status as procedure_source_status,
COALESCE(
    fhir.category.text, (SELECT coding.display from UNNEST(fhir.category.coding) as coding)
) as procedure_source_type,
(SELECT coding.code from UNNEST(fhir.category.coding) as coding) as procedure_source_type_code,
coding.system as procedure_source_system,
coding.display as procedure_source_value,
coding.code.provided as procedure_source_provided,
coding.code.integer as procedure_source_integer,
coding.code.string as procedure_source_string

FROM base, UNNEST(fhir.code.coding) as coding
)

SELECT * EXCEPT(procedure_source_provided, procedure_source_integer, procedure_source_string),
CASE WHEN procedure_source_provided LIKE "string" THEN procedure_source_string
WHEN procedure_source_provided LIKE "integer" THEN CAST(procedure_source_integer AS STRING)
END AS procedure_source_concept_id
FROM intermediate

