config {
    type: "view"
}

WITH norm AS (
  SELECT
  n.* EXCEPT(conditionMappings),
    cm.id AS mapping_id
  FROM `healthtree-production.HT_test_sync.apps-curehub-medicalResources-normalizations-Condition` n,
       UNNEST(n.conditionMappings) cm
       WHERE 
       (n.migratedFromRailsHealthtree = false OR n.migratedFromRailsHealthtree IS NULL) AND
(n.success = true) AND
(n.useInLogicDisallowed = false OR n.useInLogicDisallowed IS NULL) AND
n.user.id IN (SELECT ap.person_source_value FROM ${ref("allPersons")} ap)
AND (sourceName IS NULL OR sourceName != "HEALTH_TREE_AI" OR (validated AND isCorrect))
),

map_cm AS (
  SELECT
    concept_code AS mapping_id,
    concept_id,
    concept_name,
    vocabulary_id,
    concept_class_id,
    standard_concept
  FROM ${ref("SNOMED")}
),

r4 AS(
SELECT * FROM `healthtree-production.HT_test_sync.apps-curehub-medicalResources-r4-Condition`
WHERE
(migratedFromRailsHealthtree = false OR migratedFromRailsHealthtree IS NULL)
AND 
id IN (SELECT DISTINCT medicalResource.id FROM norm)
AND
(source.name IS NULL OR source.name != 'HEALTH_TREE_AI')
),

--norm records: 44,680
--r4 records: 40,631

intermediate AS (

SELECT
ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS condition_occurrence_id,
norm.user.id AS person_source_value,
p.person_id AS person_id,
map_cm.concept_id AS condition_concept_id,

COALESCE(
  r4.fhir.onsetPeriod.start,
  SAFE_CAST(r4.fhir.onsetDateTime AS DATE),
  SAFE_CAST(r4.fhir.recordedDate AS DATE),
  DATE(r4.recordedDate),
  DATE(norm.onsetDateTime),
  DATE(norm.recordedDate)
) AS condition_start_DATE,
COALESCE(
  DATETIME(r4.fhir.onsetPeriod.start),
  DATETIME(SAFE_CAST(r4.fhir.onsetDateTime AS TIMESTAMP)),
  DATETIME(SAFE_CAST(r4.fhir.recordedDate AS TIMESTAMP)),
  DATETIME(r4.recordedDate),
  DATETIME(norm.onsetDateTime),
  DATETIME(SAFE_CAST(norm.recordedDate AS TIMESTAMP))
) AS condition_start_DATETIME,

COALESCE(
  r4.fhir.abatementPeriod.end,
  SAFE_CAST(r4.fhir.abatementDateTime AS DATE)
) AS condition_end_DATE,
COALESCE(
  DATETIME(r4.fhir.abatementPeriod.end),
  SAFE_CAST(r4.fhir.abatementDateTime AS DATETIME)
) AS condition_end_DATETIME,

CASE
WHEN r4.fhir IS NULL THEN 0
WHEN LOWER(r4.fhir.category[SAFE_OFFSET(0)].text) like "%encounter%" THEN 32020
WHEN LOWER(r4.fhir.category[SAFE_OFFSET(0)].text) like "%problem list%" THEN 38000245
WHEN LOWER(r4.fhir.category[SAFE_OFFSET(0)].text) like "%primary%" THEN 44786628
WHEN LOWER(r4.fhir.category[SAFE_OFFSET(0)].text) like "%secondary%" THEN 44786629
ELSE 32817 END
AS condition_type_concept_id,
NULL AS stop_reason,
NULL AS provider_id,
r4.fhir.encounter.reference AS visit_occurrence_source_value,
vo.visit_occurrence_id as visit_occurrence_id,
map_cm.concept_name AS condition_source_value,
map_cm.concept_id AS condition_source_concept_id,
norm.mapping_id AS condition_source_code,
COALESCE(
  r4.fhir.clinicalStatus.text,
  r4.fhir.verificationStatus.text
) AS condition_status_source_value,
CASE
WHEN LOWER(COALESCE(
  r4.fhir.clinicalStatus.text,
  r4.fhir.verificationStatus.text
)) LIKE "%resolved%" THEN 32906
ELSE 0 END
AS condition_status_concept_id

FROM norm LEFT JOIN map_cm ON norm.mapping_id = map_cm.mapping_id
LEFT JOIN r4 ON norm.medicalResource.id = r4.id
LEFT JOIN ${ref("person")} p ON norm.user.id = p.person_source_value
LEFT JOIN ${ref("visit_occurrence")} vo ON r4.fhir.encounter.reference = vo.fhir_record_id
)

SELECT DISTINCT * FROM intermediate
