-- episode (TABLE)
config { type: "table" }

WITH person_norm AS (
  SELECT
    -- normaliza person_source_value: quita prefijos y estandariza a minúsculas
    REPLACE(LOWER(CAST(person_source_value AS STRING)), 'patient/', '') AS src_norm,
    MIN(person_id) AS person_id   -- por si hay duplicados de origen, toma el mínimo estable
  FROM ${ref("person")}
  GROUP BY 1
),
lot_base AS (
  SELECT * FROM ${ref("lot_base")}
)
SELECT
  eidx.episode_id,
  p.person_id,
  32941 AS episode_concept_id,
  DATE(lb.startDate) AS episode_start_date,
  lb.startDate       AS episode_start_datetime,
  DATE(lb.endDate)   AS episode_end_date,
  lb.endDate         AS episode_end_datetime,
  0 AS episode_parent_id,
  0 AS episode_number,
  CASE lb.diseaseName
    WHEN "cll"                 THEN 138379
    WHEN "GxAhXAnh3drV4xY5Vf3A" THEN 437233
    WHEN "WCJo8IouncjDW6exT1YS" THEN 140352
    WHEN "EkjGB5kileTKP2vnTWhV" THEN 4147411
    WHEN "WNjIFmDibXhTFneCh4dG" THEN 133169
    WHEN "t8f3E99OdM9XZe1d1ASM" THEN 138994
    WHEN "eBIxYtdHAYhTTs5L9bcC" THEN 432574
  END AS episode_object_concept_id,
  32817 AS episode_type_concept_id,
  lb.diseaseName AS episode_source_value,
  0 AS episode_source_concept_id
FROM lot_base lb
JOIN ${ref("episode_idx")} eidx USING (lineId)
LEFT JOIN person_norm p
  ON REPLACE(LOWER(CAST(lb.userId AS STRING)), 'patient/', '') = p.src_norm

  WHERE person_id IS NOT NULL
