config {
    type: "table"
}

WITH base_med AS(
SELECT es.*, des.drug_exposure_id, des.record_source_id, des.fhir_record_id, des.person_id, des.person_source_value, mri.* EXCEPT(userId)
from ${ref("episode_seeds")} es
LEFT JOIN ${ref("drug_exposure_semi")} des
ON es.item_name = des.record_source_id

LEFT JOIN ${ref("medReq_idx")} mri
ON des.record_source_id = mri.record_source_id

WHERE es.item_kind like "MedicationRequest"),

base_proc AS (
    SELECT es.*, pos.procedure_occurrence_id, pos.person_id FROM ${ref("episode_seeds")} es
    LEFT JOIN ${ref("procedure_occurrence_semi")} pos
    ON es.item_name = pos.record_source_id

    WHERE es.item_kind like "Procedure"
),

unify AS (

SELECT lineId, base_med.userId, null as stage, reference, type, source_field, des.drug_exposure_id omop_id, des.person_id
FROM base_med LEFT JOIN ${ref("drug_exposure_semi")} des ON base_med.reference = des.fhir_record_id
WHERE des.drug_exposure_id IS NOT NULL

UNION ALL

SELECT lineId, base_proc.userId, null as stage, item_name, item_kind, "_procedure_", pos.procedure_occurrence_id omop_id, pos.person_id
FROM base_proc LEFT JOIN ${ref("procedure_occurrence_semi")} pos ON base_proc.item_name = pos.fhir_record_id
WHERE pos.procedure_occurrence_id IS NOT NULL

UNION ALL

SELECT lineId, userId, es.stage, item_name, item_kind, "-medicationRequest_", des.drug_exposure_id omop_id, des.person_id
FROM ${ref("episode_seeds")} es LEFT JOIN ${ref("drug_exposure_semi")} des
ON item_name = des.record_source_id OR item_name = des.fhir_record_id
WHERE es.item_kind like "MedicationRequest"
)

SELECT DISTINCT * FROM unify WHERE omop_id IS NOT NULL