config {
    type: "table"
}

SELECT eidx.episode_id episode_id, person.person_id, 32533 episode_concept_id,
DATE(lot.startDate) AS episode_start_date,
lot.startDate AS episode_start_datetime,
DATE(lot.endDate) AS episode_end_date,
lot.endDate AS episode_end_datetime,
0 episode_parent_id, 0 episode_number,
CASE lot.diseaseName WHEN "cll" THEN 138379
WHEN "GxAhXAnh3drV4xY5Vf3A" THEN 437233
WHEN "WCJo8IouncjDW6exT1YS" THEN 140352
WHEN "EkjGB5kileTKP2vnTWhV" THEN 4147411
WHEN "WNjIFmDibXhTFneCh4dG" THEN 133169
WHEN "t8f3E99OdM9XZe1d1ASM" THEN 138994
WHEN "eBIxYtdHAYhTTs5L9bcC" THEN 432574
END AS episode_object_concept_id,
32817 episode_type_concept_id, lot.diseaseName episode_source_value, 0 episode_source_concept_id
FROM ${ref("lot_plain")} lot
LEFT JOIN ${ref("episode_idx")} eidx ON lot.lineId = eidx.lineId
LEFT JOIN ${ref("person")} person ON lot.userId = person.person_source_value



--cll 138379
--GxAhXAnh3drV4xY5Vf3A 437233
--WCJo8IouncjDW6exT1YS 140352
--EkjGB5kileTKP2vnTWhV 4147411
--WNjIFmDibXhTFneCh4dG 133169
--t8f3E99OdM9XZe1d1ASM 138994
--eBIxYtdHAYhTTs5L9bcC 432574

-- episode_type_concept_id 32817