-- lot_base (VIEW)
config { type: "view" }

WITH raw AS (
  SELECT
    `__key__`.name AS lineId,
    user.name      AS userId,
    disease.kind   AS diseaseKind,
    disease.name   AS diseaseName,
    startDate,
    endDate,
    bestOutcome,
    lastOutcome
  FROM `healthtree-production.HT.linesOfTherapy`
)
SELECT
  lineId, userId, diseaseKind, diseaseName, startDate, endDate, bestOutcome, lastOutcome
FROM raw
