config { type: "view" }

-- Mapea tu enfermedad a SNOMED si tienes varias; aquí muestro un CASE de ejemplo.
WITH disease_map AS (
  SELECT 'cll' AS diseaseName, 138379  AS disease_snomed UNION ALL
  SELECT 'GxAhXAnh3drV4xY5Vf3A', 437233 UNION ALL
  SELECT 'WCJo8IouncjDW6exT1YS', 140352 UNION ALL
  SELECT 'EkjGB5kileTKP2vnTWhV', 4147411 UNION ALL
  SELECT 'WNjIFmDibXhTFneCh4dG', 133169  UNION ALL
  SELECT 't8f3E99OdM9XZe1d1ASM', 138994  UNION ALL
  SELECT 'eBIxYtdHAYhTTs5L9bcC', 432574
)
SELECT
  lineId,
  person_id,
  episode_number,
  32941 AS episode_concept_id,                 -- Cancer Drug Treatment
  CAST(NULL AS INT64) AS episode_parent_id,    -- padre no tiene parent
  COALESCE(dm.disease_snomed, 437233) AS episode_object_concept_id, -- SNOMED de la neoplasia
  DATE(startDate) AS episode_start_date,
  startDate       AS episode_start_datetime,
  DATE(endDate)   AS episode_end_date,
  endDate         AS episode_end_datetime,
  userId, diseaseKind, lwp.diseaseName
FROM ${ref("lot_with_person_and_number")} lwp
LEFT JOIN disease_map dm USING (diseaseName)